### ISSUE TITLE
TypeError: zip argument #1 must support iteration

### ISSUE THREAD

**Issue by hiepbk** [Xharlie/BtcDet#19]
Hello author,
i tried to generate the data infos by running the following command:
python -m btcdet.datasets.kitti.kitti_dataset create_kitti_infos tools/cfgs/dataset_configs/kitti_dataset.yaml
but I got a traceback:

Traceback (most recent call last):
  File "/home/hiepubt/anaconda3/envs/btcdet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hiepubt/anaconda3/envs/btcdet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hiepubt/BtcDet/btcdet/datasets/kitti/kitti_dataset.py", line 548, in <module>
    save_path=path
  File "/home/hiepubt/BtcDet/btcdet/datasets/kitti/kitti_dataset.py", line 475, in create_kitti_infos
    kitti_infos_train = dataset.get_infos(num_workers=workers, has_label=True, count_inside_pts=True)
  File "/home/hiepubt/BtcDet/btcdet/datasets/kitti/kitti_dataset.py", line 200, in get_infos
    infos = executor.map(process_single_scene, sample_id_list)
  File "/home/hiepubt/anaconda3/envs/btcdet/lib/python3.7/concurrent/futures/_base.py", line 587, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
TypeError: zip argument #1 must support iteration

**Comment by tnb918** [comment]
Pay attention to add ImageSets files

**Comment by hiepbk** [comment]
> Pay attention to add ImageSets files

Hello bro, Can you tell me what is the ImageSets files?

**Comment by tnb918** [comment]
You can refer to this，https://github.com/open-mmlab/OpenPCDet/tree/master/data/kitti/ImageSets

**Comment by hiepbk** [comment]
Thank you bro, you save my life =)))

**Comment by libingDY** [comment]
Hello, I have the same error. Why didn't I solve it? Could you show me the data directory
