### ISSUE TITLE
RuntimeError: No CUDA GPUs are available

### ISSUE THREAD

**Issue by hiepbk** [Xharlie/BtcDet#28]
Hello everyone,
I got an error when I runned this command: python -m btcdet.datasets.multifindbestfit
Its traceback:
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "/home/hiepubt/anaconda3/envs/btc/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hiepubt/anaconda3/envs/btc/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hiepubt/BtcDet/btcdet/datasets/multifindbestfit.py", line 21, in <module>
    from ..ops.chamfer_distance import ChamferDistance
  File "/home/hiepubt/BtcDet/btcdet/ops/chamfer_distance/__init__.py", line 1, in <module>
    from .chamfer_distance import ChamferDistance
  File "/home/hiepubt/BtcDet/btcdet/ops/chamfer_distance/chamfer_distance.py", line 11, in <module>
    cd = load(name="cd",sources=[cpp_file,cu_file])
  File "/home/hiepubt/anaconda3/envs/btc/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 980, in load
    keep_intermediates=keep_intermediates)
  File "/home/hiepubt/anaconda3/envs/btc/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1185, in _jit_compile
    with_cuda=with_cuda)
  File "/home/hiepubt/anaconda3/envs/btc/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1276, in _write_ninja_file_and_build_library
    with_cuda=with_cuda)
  File "/home/hiepubt/anaconda3/envs/btc/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1602, in _write_ninja_file_to_build_library
    cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
  File "/home/hiepubt/anaconda3/envs/btc/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1407, in _get_cuda_arch_flags
    capability = torch.cuda.get_device_capability()
  File "/home/hiepubt/anaconda3/envs/btc/lib/python3.7/site-packages/torch/cuda/__init__.py", line 291, in get_device_capability
    prop = get_device_properties(device)
  File "/home/hiepubt/anaconda3/envs/btc/lib/python3.7/site-packages/torch/cuda/__init__.py", line 296, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/home/hiepubt/anaconda3/envs/btc/lib/python3.7/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
Can anyone help me about this issue?

**Comment by 123jyw** [comment]
Please ask if you have solved it now
