### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by cdiazruiz** [Xharlie/BtcDet#39]
Getting an error when I run: 
python -m btcdet.datasets.kitti.kitti_dataset create_kitti_infos tools/cfgs/dataset_configs/kitti_dataset.yaml

/home/cad297/anaconda3/envs/btc/lib/python3.6/runpy.py:125: RuntimeWarning: 'btcdet.datasets.kitti.kitti_dataset' found in sys.modules after import of package 'btcdet.datasets.kitti', but prior to execution of 'btcdet.datasets.kitti.kitti_dataset'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/home/cad297/projects/BtcDet/btcdet/datasets/kitti/kitti_dataset.py:539: YAMLLoadWarning:calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  dataset_cfg = EasyDict(yaml.load(open(sys.argv[2])))
ROOT_DIR /home/cad297/projects/BtcDet
cur_cfg.NAME mask_points_and_boxes_outside_range
cur_cfg.NAME shuffle_points
cur_cfg.NAME transform_points_to_voxels
self.dataset_cfg.INFO_PATH {'train': ['kitti_infos_train.pkl'], 'test': ['kitti_infos_val.pkl']}
---------------Start to generate data infos---------------
cur_cfg.NAME mask_points_and_boxes_outside_range
cur_cfg.NAME shuffle_points
cur_cfg.NAME transform_points_to_voxels
Traceback (most recent call last):
  File "/home/cad297/anaconda3/envs/btc/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/cad297/anaconda3/envs/btc/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cad297/projects/BtcDet/btcdet/datasets/kitti/kitti_dataset.py", line 548, in <module>
    save_path=path
  File "/home/cad297/projects/BtcDet/btcdet/datasets/kitti/kitti_dataset.py", line 475, in create_kitti_infos
    kitti_infos_train = dataset.get_infos(num_workers=workers, has_label=True, count_inside_pts=True)
  File "/home/cad297/projects/BtcDet/btcdet/datasets/kitti/kitti_dataset.py", line 201, in get_infos
    return list(infos)
  File "/home/cad297/anaconda3/envs/btc/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/home/cad297/anaconda3/envs/btc/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/cad297/anaconda3/envs/btc/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/cad297/anaconda3/envs/btc/lib/python3.6/concurrent/futures/thread.py", line56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/cad297/projects/BtcDet/btcdet/datasets/kitti/kitti_dataset.py", line 158, in process_single_scene
    annotations['bbox'] = np.concatenate([obj.box2d.reshape(1, 4) for obj in obj_list], axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

Anyone seen the same? Or have been able to fix?

**Comment by cdiazruiz** [comment]
fixed. my label_2 .txt  had an empty file for some reason
