### ISSUE TITLE
ModuleNotFoundError: No module named 'btcdet.utils'

### ISSUE THREAD

**Issue by yeoeun-oh** [Xharlie/BtcDet#40]
after 'python3 setup.py develop'

Traceback (most recent call last):
  File "train.py", line 6, in <module>
    from test import repeat_eval_ckpt
  File "/tmp/BtcDet/tools/test.py", line 14, in <module>
    from btcdet.datasets import build_dataloader
  File "/usr/local/lib/python3.6/dist-packages/btcdet/datasets/__init__.py", line 5, in <module>
    from btcdet.utils import common_utils
ModuleNotFoundError: No module named 'btcdet.utils'

**Comment by DheerajYarlagadda** [comment]
try:
import sys 
sys.path.append("/path/to/dir")
